kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: registry.typex.one/env/chess-build-env:v1.0
    commands:
      - cmake -S .
      - make
  - name: test
    image: registry.typex.one/env/pwntools:v1.0
    commands:
      - python3 ./tests.py
  - name: publish
    image: registry.typex.one/env/kaniko:v1.5.1
    settings:
      registry: registry.oceancraft.ru
      repo: k8s/chess-server
      tags:
        - ${DRONE_COMMIT_SHA}
      cache: true
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      branch:
        - master
  - name: deploy
    image: registry.typex.one/env/helm:3.4.1f
    environment:
      KUBECONFIG: /etc/deploy/config
      kube_config:
        from_secret: K8S_CONFIG
      REGISTRY_USER:
        from_secret: REGISTRY_USER
      REGISTRY_PASSWORD:
        from_secret: REGISTRY_PASSWORD
    commands:
      - mkdir -p /etc/deploy
      - echo $kube_config | base64 -d >> $KUBECONFIG
      - chmod 700 $KUBECONFIG
      - helm upgrade --wait --atomic --install chess-game . --namespace=chess-game --set=image.tag=$DRONE_COMMIT_SHA --set=imageCredentials.username=$REGISTRY_USER --set=imageCredentials.password=$REGISTRY_PASSWORD
    when:
      branch:
        - master

image_pull_secrets:
  - pull_secret