apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  labels: {{- include "chess-server.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}