apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess-server.fullname" . }}
  labels:
    {{- include "chess-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30881
      protocol: TCP
  selector:
    {{- include "chess-server.selectorLabels" . | nindent 4 }}
